export const CHECKOUT_STATUS = {
  STARTING_CHECKOUT: 'STARTING_CHECKOUT',
  ADDRESS_SUBMITTING: 'ADDRESS_SUBMITTING',
  PAYMENT_SUBMITTING: 'PAYMENT_SUBMITTING',  
  ORDER_SUBMITTING: 'ORDER_SUBMITTING',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
};
