export const CHECKOUT_STATUS = {
  STARTING_CHECKOUT: 'STARTING_CHECKOUT',
  ADDRESS_SUBMITTING: 'ADDRESS_SUBMITTING',
  ADDRESS_SUBMITTED: 'ADDRESS_SUBMITTED',  
  PAYMENT_SUBMITTING: 'PAYMENT_SUBMITTING',  
  PAYMENT_SUBMITTED: 'PAYMENT_SUBMITTED',
  ORDER_SUBMITTING: 'ORDER_SUBMITTING',
  ORDER_SUBMITTED: 'ORDER_SUBMITTED',  
  ORDER_COMPLETED: 'ORDER_COMPLETED',
};
